aca-py start \
    -it http 0.0.0.0 80 \
    -ot http \
    -e $ACAPY_ENDPOINT \
    --label $AGENT_NAME \
    --auto-accept-requests --auto-ping-connection \
    --auto-respond-credential-proposal --auto-respond-credential-offer --auto-respond-credential-request --auto-store-credential \
    --auto-respond-presentation-proposal --auto-respond-presentation-request --auto-verify-presentation \
    --invite --invite-role admin --invite-label "$AGENT_NAME (admin)" \
    --genesis-url $GENESIS_URL \
    --wallet-type indy \
    --wallet-name $AGENT_NAME \
    --plugin acapy_plugin_toolbox
